"$schema" = "./node_modules/wrangler/config-schema.json"
name = "quantwave"
pages_build_output_dir = "./dist"
compatibility_date = "2026-05-09"

[[kv_namespaces]]
binding = "KV"
id = "439f6ce76ae94b49b1f3de53e64df1ea"
